
from enum import IntEnum

class BlockStatus(IntEnum):
    INVALID_PREVHASH = -1
    INVALID_DIFFICULTY = -2
    INVALID_POW = -3
    INVALID_DUPLICATE = -4
    
    INVALID_TX_MULTIPLE_REWARDS = -5
    INVALID_TX_INVALID_REWARD = -6
    INVALID_TX_WRONG_REWARD_AMOUNT = -7
    INVALID_TX = -8
    INVALID_TX_UTXO_IS_SPENT = -9

    INVALID_ERROR = 0

    VALID = 1
